// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqnsyrybqmjbvlgpmzgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxbnN5cnlicW1qYnZsZ3Btemd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1MTgyNTQsImV4cCI6MjA5ODA5NDI1NH0.4akpOOYT-nRANU2MhX3vbDXtMNh3OO-v5YPEGmibbzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});